pipeline {
	agent { 
		node {
      		label 'jenkins-slave11.yvu.ch'
    	}
	}
	stages {
		stage('Build') {
			steps {
				sh 'echo Build'
				sh 'cd Gadgeothek; ./gradlew build'
			}
		}

		stage('End2End Tests') {
		    steps {
		        sh 'echo End2End Tests'
		    }
		}

		stage('Package') {
		    steps {
		        sh 'echo Package'
		    }
		}
	}
	post {
	    always {
    	    archiveArtifacts '**/outputs/apk/*.apk'
    	    cleanWs()
	    }
	}
}
